# Generated by Django 2.2.2 on 2019-07-02 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('push_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论次数')),
                ('like_num', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('content', models.FileField(unique=True, upload_to='media/article', verbose_name='博客文件')),
                ('content_name', models.CharField(max_length=32, unique=True, verbose_name='博客文件名')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner', verbose_name='轮播图片')),
                ('order_num', models.IntegerField(default=0, verbose_name='播出顺序')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ANTblog.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='ANTblog.Tag'),
        ),
    ]
