# Generated by Django 2.2.2 on 2019-07-02 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='评论次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(unique=True, upload_to='media/article/%Y/%m/%d/', verbose_name='博客文件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='喜欢人数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='look_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='push_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
    ]
