# Generated by Django 2.2.2 on 2019-07-02 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0003_auto_20190702_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='push_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='push_time',
        ),
        migrations.AddField(
            model_name='article',
            name='push_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='上传时间'),
        ),
    ]
