# Generated by Django 2.2.2 on 2019-07-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0005_auto_20190702_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guess_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='./article/image/', verbose_name='缩略图'),
        ),
    ]
