# Generated by Django 2.2.2 on 2019-07-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0006_auto_20190702_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='css',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'sec'), (3, 'thrid')], default=1),
        ),
    ]
