# Generated by Django 2.2.2 on 2019-07-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0008_auto_20190703_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=512, verbose_name='文章简介'),
        ),
    ]
