# Generated by Django 2.2.2 on 2019-07-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0009_auto_20190703_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(max_length=335, verbose_name='文章简介'),
        ),
    ]
