# Generated by Django 2.2.2 on 2019-07-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0012_auto_20190711_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ANTblog.Reply'),
        ),
    ]
