# Generated by Django 2.2.2 on 2019-07-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0013_auto_20190711_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='分类名')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序号')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ANTblog.Category')),
            ],
            options={
                'verbose_name': '博客类别',
                'verbose_name_plural': '博客类别',
                'ordering': ('order_num', 'add_datetime'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ANTblog.Category'),
        ),
    ]
