# Generated by Django 2.2.2 on 2019-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0015_auto_20190712_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path_name',
            field=models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='路径名'),
        ),
    ]
