# Generated by Django 2.2.2 on 2019-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0017_auto_20190712_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_child',
            field=models.BooleanField(default=True, verbose_name='是否有子菜单'),
        ),
    ]
