# Generated by Django 2.2.2 on 2019-07-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANTblog', '0018_category_has_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent_id', 'order_num', 'add_datetime'), 'verbose_name': '博客类别', 'verbose_name_plural': '博客类别'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default=None, help_text='fontawesome里获取', max_length=128, null=True, verbose_name='图标'),
        ),
    ]
